# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'last2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 735)
        MainWindow.setStyleSheet("/* =====================================================\n"
"   MAIN WINDOW - PREMIUM MONOCHROME GRADIENT\n"
"   ===================================================== */\n"
"QMainWindow#MainWindow {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #0B0F20,\n"
"        stop:0.4 #121A33,\n"
"        stop:0.7 #0C1125,\n"
"        stop:1 #0B0F20\n"
"    );\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    color: #E0E7FF;\n"
"}\n"
"\n"
"/* =====================================================\n"
"   CENTRAL WIDGETS\n"
"   ===================================================== */\n"
"QWidget#centralWidget_2,\n"
"QWidget#centralWidget {\n"
"    background: rgba(255,255,255,0.04);\n"
"    border-radius: 24px;\n"
"    border: 1px solid rgba(79,139,255,0.3);\n"
"}\n"
"\n"
"/* =====================================================\n"
"   CARD FRAME\n"
"   ===================================================== */\n"
"QFrame#cardFrame {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgba(18,18,55,0.9),\n"
"        stop:1 rgba(38,38,95,0.9)\n"
"    );\n"
"    border-radius: 28px;\n"
"    border: 1px solid rgba(79,139,255,0.6);\n"
"}\n"
"\n"
"/* =====================================================\n"
"   FUNCTION BUTTONS (TOP ROW) - VERY THIN/FLAT\n"
"   ===================================================== */\n"
"QPushButton#Compression,\n"
"QPushButton#Decompresssion,\n"
"QPushButton#Prettifying,\n"
"QPushButton#XMLconsistency,\n"
"QPushButton#Minifying,\n"
"QPushButton#XMLtoJSON {\n"
"    background: rgba(255,255,255,0.05);\n"
"    height: 35px;\n"
"    min-width: 100px;\n"
"    padding: 8px 20px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    color: #ffffff;\n"
"    border-radius: 20px;\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"}\n"
"\n"
"QPushButton#Compression:hover,\n"
"QPushButton#Decompresssion:hover,\n"
"QPushButton#Prettifying:hover,\n"
"QPushButton#XMLconsistency:hover,\n"
"QPushButton#Minifying:hover,\n"
"QPushButton#XMLtoJSON:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c084fc,\n"
"        stop:0.2 #a78bfa,\n"
"        stop:0.5 #818cf8,\n"
"        stop:0.8 #60a5fa,\n"
"        stop:1 #3b82f6\n"
"    );\n"
"    box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"    border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#Compression:pressed,\n"
"QPushButton#Decompresssion:pressed,\n"
"QPushButton#Prettifying:pressed,\n"
"QPushButton#XMLconsistency:pressed,\n"
"QPushButton#Minifying:pressed,\n"
"QPushButton#XMLtoJSON:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #a855f7,\n"
"        stop:0.2 #8b5cf6,\n"
"        stop:0.5 #6366f1,\n"
"        stop:0.8 #3b82f6,\n"
"        stop:1 #2563eb\n"
"    );\n"
"    box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}\n"
"\n"
"/* =====================================================\n"
"   TEXT EDITOR - READ ONLY STYLE\n"
"   ===================================================== */\n"
"QTextEdit#textEdit {\n"
"    padding: 18px;\n"
"    font-size: 14px;\n"
"    font-family: \"Consolas\", \"Courier New\", monospace;\n"
"    color: #E0E7FF;\n"
"    background: rgba(255,255,255,0.06);\n"
"    border-radius: 18px;\n"
"    border: 1px solid rgba(79,139,255,0.45);\n"
"    box-shadow: inset 0 0 8px rgba(79,139,255,0.2);\n"
"}\n"
"\n"
"QTextEdit#textEdit:hover {\n"
"    border: 1px solid #4F8BFF;\n"
"    box-shadow: 0 0 16px #4F8BFF, inset 0 0 8px rgba(79,139,255,0.25);\n"
"}\n"
"\n"
"QTextEdit#textEdit:focus {\n"
"    border: 2px solid #2563EB;\n"
"    box-shadow: 0 0 25px #2563EB, inset 0 0 12px rgba(79,139,255,0.3);\n"
"}\n"
"/* =====================================================\n"
"   SIDE BUTTONS (save, new, new_2, graph) - 110px WIDTH\n"
"   ===================================================== */\n"
"QPushButton#graph,\n"
"QPushButton#save,\n"
"QPushButton#new,\n"
"QPushButton#new_2 {\n"
"    height: 40px;\n"
"    width: 110px;\n"
"    padding: 8px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: 700;\n"
"    color: #E0E7FF;\n"
"    border-radius: 20px;\n"
"    border: none;\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #c084fc,\n"
"        stop:0.2 #a78bfa,\n"
"        stop:0.5 #818cf8,\n"
"        stop:0.8 #60a5fa,\n"
"        stop:1 #3b82f6\n"
"    );\n"
"    box-shadow: 0 8px 35px rgba(139,92,246,0.8), 0 0 50px rgba(99,102,241,0.5);\n"
"}\n"
"\n"
"QPushButton#graph:hover,\n"
"QPushButton#save:hover,\n"
"QPushButton#new:hover,\n"
"QPushButton#new_2:hover {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #a855f7,\n"
"        stop:0.2 #8b5cf6,\n"
"        stop:0.5 #6366f1,\n"
"        stop:0.8 #3b82f6,\n"
"        stop:1 #2563eb\n"
"    );\n"
"    box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"    border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#graph:pressed,\n"
"QPushButton#save:pressed,\n"
"QPushButton#new:pressed,\n"
"QPushButton#new_2:pressed {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #8b5cf6,\n"
"        stop:0.5 #6366f1,\n"
"        stop:1 #3b82f6\n"
"    );\n"
"    box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}\n"
"/* =====================================================\n"
"   SCROLL BARS (FOR TEXT EDITOR)\n"
"   ===================================================== */\n"
"QScrollBar:vertical {\n"
"    background: rgba(255,255,255,0.03);\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(79,139,255,0.4);\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(79,139,255,0.6);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: rgba(255,255,255,0.03);\n"
"    height: 12px;\n"
"    border-radius: 6px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(79,139,255,0.4);\n"
"    border-radius: 6px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(79,139,255,0.6);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"/* =====================================================\n"
"   MENU BAR - PREMIUM STYLE WITH ROUNDED CORNERS\n"
"   ===================================================== */\n"
"QMenuBar {\n"
"    background: rgba(18,18,55,0.8);\n"
"    color: #E0E7FF;\n"
"    border-bottom: 1px solid rgba(79,139,255,0.3);\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 8px 16px;\n"
"    border-radius: 12px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: rgba(79,139,255,0.2);\n"
"    border: 1px solid rgba(79,139,255,0.4);\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    background: rgba(79,139,255,0.3);\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/* =====================================================\n"
"   MENU DROPDOWN - PREMIUM STYLE WITH ROUNDED CORNERS\n"
"   ===================================================== */\n"
"QMenu {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 rgba(18,18,55,0.95),\n"
"        stop:1 rgba(28,28,75,0.95)\n"
"    );\n"
"    color: #E0E7FF;\n"
"    border: 1px solid rgba(79,139,255,0.5);\n"
"    border-radius: 16px;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 10px 30px 10px 20px;\n"
"    border-radius: 10px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(139,92,246,0.3),\n"
"        stop:1 rgba(99,102,241,0.3)\n"
"    );\n"
"    border: 1px solid rgba(139,92,246,0.5);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background: rgba(79,139,255,0.3);\n"
"    margin: 5px 10px;\n"
"    border-radius: 1px;\n"
"}")
        self.centralWidget_2 = QtWidgets.QWidget(MainWindow)
        self.centralWidget_2.setObjectName("centralWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.centralWidget = QtWidgets.QWidget(self.centralWidget_2)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rootLayout = QtWidgets.QVBoxLayout()
        self.rootLayout.setObjectName("rootLayout")
        self.cardFrame = QtWidgets.QFrame(self.centralWidget)
        self.cardFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.cardFrame.setStyleSheet("")
        self.cardFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cardFrame.setObjectName("cardFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.cardFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 586, 62))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(52, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 44))
        self.label_2.setStyleSheet("/* For a single Label */\n"
"QLabel {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"   /* background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(99, 179, 237, 0.15),\n"
"        stop:1 rgba(159, 122, 234, 0.15));*/\n"
"    \n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    height: 28px;\n"
"    min-width:20px;\n"
"}\n"
"/*    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 2px solid rgba(79,139,255,0.45);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dropdown_menu = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.dropdown_menu.setStyleSheet("QComboBox {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"/*QComboBox:hover {\n"
"    border-color: rgba(99, 179, 237, 1.0);\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    //    stop:0 rgba(59, 130, 246, 0.35),\n"
"  //      stop:1 rgba(99, 102, 241, 0.35));\n"
"//}*/\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid rgba(79,139,255,0.45);\n"
"    background: rgba(255,255,255,0.05);/*qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(59, 130, 246, 0.3),\n"
"        stop:1 rgba(99, 102, 241, 0.3));*/\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"   border: 1px solid rgba(79,139,255,0.45);\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 6px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: white;\n"
"    background-color: #0f1b2d;\n"
"    border: 2px solid rgba(168,85,247,0.8);\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    outline: none;\n"
"    selection-background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(59, 130, 246, 0.5),\n"
"        stop:1 rgba(99, 102, 241, 0.5));\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    min-height: 60px;\n"
"    padding-top: 20px;\n"
"    padding-bottom: 20px;\n"
"    padding-left: 14px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: rgba(99, 179, 237, 0.2);\n"
"    color: #63b3ed;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(59, 130, 246, 0.5),\n"
"        stop:1 rgba(99, 102, 241, 0.5));\n"
"    color: white;\n"
"}")
        self.dropdown_menu.setObjectName("dropdown_menu")
        self.dropdown_menu.addItem("")
        self.dropdown_menu.addItem("")
        self.dropdown_menu.addItem("")
        self.dropdown_menu.addItem("")
        self.dropdown_menu.addItem("")
        self.dropdown_menu.addItem("")
        self.horizontalLayout.addWidget(self.dropdown_menu)
        self.label = QtWidgets.QLabel(self.cardFrame)
        self.label.setGeometry(QtCore.QRect(320, 30, 361, 61))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.cardFrame)
        self.checkBox.setGeometry(QtCore.QRect(30, 170, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.checkBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setStyleSheet("    color: white;")
        self.checkBox.setObjectName("checkBox")
        self.tableWidget = QtWidgets.QTableWidget(self.cardFrame)
        self.tableWidget.setGeometry(QtCore.QRect(450, 340, 301, 271))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    padding: 4px;\n"
"    font-size: 13px;\n"
"    color: #E0E7FF;\n"
"    background: rgba(255,255,255,0.06);\n"
"    border-radius: 18px;\n"
"    border: 2px solid rgba(79,139,255,0.45);\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: rgba(255,255,255,0.06);\n"
"    color: white;\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    height: 24px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 2px 6px;\n"
"    background: rgba(255,255,255,0.04);\n"
"    border: 1px solid rgba(139,92,246,0.5);\n"
"    color: #E0E7FF;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: rgba(79,139,255,0.25);\n"
"    color: white;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background: rgba(255,255,255,0.06);\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: rgba(255,255,255,0.06);\n"
"    border: 1px solid rgba(139,92,246,0.5);\n"
"    width: 6px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(139,92,246,0.5);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background: transparent;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.textEdit = QtWidgets.QTextEdit(self.cardFrame)
        self.textEdit.setGeometry(QtCore.QRect(20, 340, 421, 271))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    padding: 18px;\n"
"    font-size: 15px;\n"
"    color: #E0E7FF;\n"
"    background: rgba(255,255,255,0.06);\n"
"    border-radius: 18px;\n"
"    border: 2px solid rgba(79,139,255,0.45);\n"
"}\n"
"\n"
"QTextEditt:hover {\n"
"    border: 2px solid #4F8BFF;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #2563EB;\n"
"}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.widget = QtWidgets.QWidget(self.cardFrame)
        self.widget.setGeometry(QtCore.QRect(20, 220, 901, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.arrival_label = QtWidgets.QLabel(self.widget)
        self.arrival_label.setMaximumSize(QtCore.QSize(170, 44))
        self.arrival_label.setStyleSheet("/* For a single Label */\n"
"QLabel {\n"
"    color: white;\n"
"   background: rgba(255,255,255,0.05);\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"height: 28px;\n"
"}")
        self.arrival_label.setObjectName("arrival_label")
        self.horizontalLayout_6.addWidget(self.arrival_label)
        self.arrival_input = QtWidgets.QSpinBox(self.widget)
        self.arrival_input.setMaximumSize(QtCore.QSize(60, 16777215))
        self.arrival_input.setStyleSheet("QSpinBox {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-top-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-bottom-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.arrival_input.setObjectName("arrival_input")
        self.horizontalLayout_6.addWidget(self.arrival_input)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.burst_label = QtWidgets.QLabel(self.widget)
        self.burst_label.setMaximumSize(QtCore.QSize(180, 44))
        self.burst_label.setStyleSheet("/* For a single Label */\n"
"QLabel {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"   border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    height: 28px;\n"
"    min-width:20px;\n"
"}")
        self.burst_label.setObjectName("burst_label")
        self.horizontalLayout_7.addWidget(self.burst_label)
        self.burst_input = QtWidgets.QSpinBox(self.widget)
        self.burst_input.setMaximumSize(QtCore.QSize(60, 16777215))
        self.burst_input.setStyleSheet("QSpinBox {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-top-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-bottom-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.burst_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.burst_input.setObjectName("burst_input")
        self.horizontalLayout_7.addWidget(self.burst_input)
        self.priority_label = QtWidgets.QLabel(self.widget)
        self.priority_label.setMaximumSize(QtCore.QSize(180, 44))
        self.priority_label.setStyleSheet("/* For a single Label */\n"
"QLabel {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    height: 28px;\n"
"    min-width:20px;\n"
"}")
        self.priority_label.setObjectName("priority_label")
        self.horizontalLayout_7.addWidget(self.priority_label)
        self.priority_input = QtWidgets.QSpinBox(self.widget)
        self.priority_input.setMaximumSize(QtCore.QSize(60, 16777215))
        self.priority_input.setStyleSheet("QSpinBox {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-top-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-bottom-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.priority_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.priority_input.setObjectName("priority_input")
        self.horizontalLayout_7.addWidget(self.priority_input)
        self.quantum_label = QtWidgets.QLabel(self.widget)
        self.quantum_label.setMaximumSize(QtCore.QSize(180, 44))
        self.quantum_label.setStyleSheet("/* For a single Label */\n"
"QLabel {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"   border: 2px solid rgba(139,92,246,0.5);\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.5px;\n"
"    height: 28px;\n"
"    min-width:20px;\n"
"}")
        self.quantum_label.setObjectName("quantum_label")
        self.horizontalLayout_7.addWidget(self.quantum_label)
        self.quantum_input = QtWidgets.QSpinBox(self.widget)
        self.quantum_input.setMaximumSize(QtCore.QSize(60, 16777215))
        self.quantum_input.setStyleSheet("QSpinBox {\n"
"    color: white;\n"
"    background: rgba(255,255,255,0.05);\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    border-radius: 10px;\n"
"    padding: 6px 14px;\n"
"    font-size: 13px;\n"
"    font-weight: 600;\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    letter-spacing: 0.4px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid rgba(168,85,247,0.8);\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-top-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 20px;\n"
"    border-left: 1px solid rgba(99, 179, 237, 0.3);\n"
"    border-bottom-right-radius: 10px;\n"
"    background: rgba(255,255,255,0.05);\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-bottom: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 4px solid transparent;\n"
"    border-right: 4px solid transparent;\n"
"    border-top: 5px solid rgba(99, 179, 237, 0.9);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.quantum_input.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.quantum_input.setObjectName("quantum_input")
        self.horizontalLayout_7.addWidget(self.quantum_input)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.cardFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(760, 350, 160, 255))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.runButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.runButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#runButton,\n"
"QPushButton#resetButton,\n"
"QPushButton#saveButton {\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#runButton:hover,\n"
"QPushButton#resetButton:hover,\n"
"QPushButton#saveButton:hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#runButton:pressed,\n"
"QPushButton#resetButton:pressed,\n"
"QPushButton#saveButton:pressed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.runButton.setObjectName("runButton")
        self.verticalLayout_2.addWidget(self.runButton)
        self.pauseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pauseButton.setAcceptDrops(False)
        self.pauseButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#runButton,\n"
"QPushButton#resetButton,\n"
"QPushButton#saveButton ,\n"
"QPushButton#pauseButton,\n"
"QPushButton#resumeButton{\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#runButton:hover,\n"
"QPushButton#resetButton:hover,\n"
"QPushButton#saveButton:hover,\n"
"QPushButton#pauseButton:hover,\n"
"QPushButton#resumeButton: hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#runButton:pressed,\n"
"QPushButton#resetButton:pressed,\n"
"QPushButton#saveButton:pressed,\n"
"QPushButton#pauseButton:pressed,\n"
"QPushButton#resumeButton:preesed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.pauseButton.setObjectName("pauseButton")
        self.verticalLayout_2.addWidget(self.pauseButton)
        self.resumeButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resumeButton.setAcceptDrops(False)
        self.resumeButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#runButton,\n"
"QPushButton#resetButton,\n"
"QPushButton#saveButton ,\n"
"QPushButton#pauseButton,\n"
"QPushButton#resumeButton{\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#runButton:hover,\n"
"QPushButton#resetButton:hover,\n"
"QPushButton#saveButton:hover,\n"
"QPushButton#pauseButton:hover,\n"
"QPushButton#resumeButton: hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#runButton:pressed,\n"
"QPushButton#resetButton:pressed,\n"
"QPushButton#saveButton:pressed,\n"
"QPushButton#pauseButton:pressed,\n"
"QPushButton#resumeButton:preesed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.resumeButton.setObjectName("resumeButton")
        self.verticalLayout_2.addWidget(self.resumeButton)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#runButton,\n"
"QPushButton#resetButton,\n"
"QPushButton#saveButton {\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#runButton:hover,\n"
"QPushButton#resetButton:hover,\n"
"QPushButton#saveButton:hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#runButton:pressed,\n"
"QPushButton#resetButton:pressed,\n"
"QPushButton#saveButton:pressed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_2.addWidget(self.resetButton)
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#runButton,\n"
"QPushButton#resetButton,\n"
"QPushButton#saveButton {\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#runButton:hover,\n"
"QPushButton#resetButton:hover,\n"
"QPushButton#saveButton:hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#runButton:pressed,\n"
"QPushButton#resetButton:pressed,\n"
"QPushButton#saveButton:pressed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton)
        self.addButton = QtWidgets.QPushButton(self.cardFrame)
        self.addButton.setGeometry(QtCore.QRect(20, 280, 171, 45))
        self.addButton.setStyleSheet("/* Add your button objectNames below */\n"
"QPushButton#addButton{\n"
"background: rgba(255,255,255,0.05);\n"
"height: 25px;\n"
"min-width: 50px;\n"
"padding: 8px 20px;\n"
"font-size: 13px;\n"
"font-weight: 600;\n"
"color: #ffffff;\n"
"border-radius: 20px;\n"
"border: 2px solid rgba(139,92,246,0.5);\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.6), 0 0 50px rgba(99,102,241,0.4);\n"
"transition: all 0.35s ease;\n"
"}\n"
"\n"
"QPushButton#addButton:hover {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #c084fc,\n"
"    stop:0.2 #a78bfa,\n"
"    stop:0.5 #818cf8,\n"
"    stop:0.8 #60a5fa,\n"
"    stop:1 #3b82f6\n"
");\n"
"box-shadow: 0 20px 70px rgba(139,92,246,1), 0 0 100px rgba(99,102,241,0.8);\n"
"border: 2px solid rgba(168,85,247,0.8);\n"
"}\n"
"\n"
"QPushButton#addButton:pressed {\n"
"background: qlineargradient(\n"
"    x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #a855f7,\n"
"    stop:0.2 #8b5cf6,\n"
"    stop:0.5 #6366f1,\n"
"    stop:0.8 #3b82f6,\n"
"    stop:1 #2563eb\n"
");\n"
"box-shadow: 0 8px 35px rgba(139,92,246,0.7), 0 0 50px rgba(99,102,241,0.5);\n"
"}")
        self.addButton.setObjectName("addButton")
        self.rootLayout.addWidget(self.cardFrame)
        self.verticalLayout.addLayout(self.rootLayout)
        self.verticalLayout_3.addWidget(self.centralWidget)
        MainWindow.setCentralWidget(self.centralWidget_2)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 50))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "CPU Algorithm"))
        self.dropdown_menu.setItemText(0, _translate("MainWindow", "First Come First Serve"))
        self.dropdown_menu.setItemText(1, _translate("MainWindow", "Shortest Job First(SJF) Preemptive"))
        self.dropdown_menu.setItemText(2, _translate("MainWindow", "Shortest Job First(SJF) Non Preemptive"))
        self.dropdown_menu.setItemText(3, _translate("MainWindow", "Priority Scheduling Preemptive"))
        self.dropdown_menu.setItemText(4, _translate("MainWindow", "Priority Scheduling Non Preemptive"))
        self.dropdown_menu.setItemText(5, _translate("MainWindow", "Round Robin"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><h1 align=\"center\" style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:600; color:#ffffff;\">CPU Scheduler</span></h1></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "live simulation"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "pid"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Burst"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "finish"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Processing results will be displayed here"))
        self.arrival_label.setText(_translate("MainWindow", "Arrival time"))
        self.burst_label.setText(_translate("MainWindow", "Burst time"))
        self.priority_label.setText(_translate("MainWindow", "priority"))
        self.quantum_label.setText(_translate("MainWindow", "quantum time"))
        self.runButton.setText(_translate("MainWindow", "run"))
        self.pauseButton.setText(_translate("MainWindow", "pause"))
        self.resumeButton.setText(_translate("MainWindow", "resume"))
        self.resetButton.setText(_translate("MainWindow", "reset"))
        self.saveButton.setText(_translate("MainWindow", "display"))
        self.addButton.setText(_translate("MainWindow", "add"))
# from qwidget_ import QWidget_


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
